### ISSUE TITLE
No value for FUNCTION_PATH found in esmtoolsrc during esm_versions upgrade

### ISSUE THREAD

**Issue by mandresm** [esm-tools/esm_version_checker#15]
When I run `esm_versions upgrade` I get the following error:
```
Traceback (most recent call last):
  File "/home/ollie/mandresm/.local/bin/esm_versions", line 8, in <module>
    sys.exit(main())
  File "/global/AWIsoft/intel-python/2020.2.902/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/global/AWIsoft/intel-python/2020.2.902/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/global/AWIsoft/intel-python/2020.2.902/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/global/AWIsoft/intel-python/2020.2.902/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/global/AWIsoft/intel-python/2020.2.902/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ollie/mandresm/.local/lib/python3.7/site-packages/esm_version_checker/cli.py", line 244, in upgrade
    pip_or_pull(tool)
  File "/home/ollie/mandresm/.local/lib/python3.7/site-packages/esm_version_checker/cli.py", line 200, in pip_or_pull
    FUNCTION_PATH = esm_rcfile.get_rc_entry("FUNCTION_PATH")
  File "/home/ollie/mandresm/.local/lib/python3.7/site-packages/esm_rcfile/esm_rcfile.py", line 118, in get_rc_entry
    raise EsmRcfileError("No value for %s found in esmtoolsrc file!" % key)
esm_rcfile.esm_rcfile.EsmRcfileError: No value for FUNCTION_PATH found in esmtoolsrc file!
```

**Comment by denizural** [comment]
I fixed that in the branch I pushed (remove_github_connection)

**Comment by mandresm** [comment]
Great! You can do then a pull request

**Comment by pgierz** [comment]
Closed via Deniz's branch.
